<?php
/**
 * @file
 * Module file for DBCDK Community.
 */

use Drupal\Core\Url;
use Drupal\user\Entity\User;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_user_login().
 */
function dbcdk_community_user_login(User $account) {
  // Redirect roles with specific focus to their primary page on login.
  // Map each role to the corresponding path. First roles take precedence in
  // case a user has multiple roles.
  $role_route_map = [
    'admin_moderator' => 'page_manager.page_view_dbcdk_community_flagged_content',
    'admin_library_employee' => 'page_manager.page_view_dbcdk_community_reviews',
    'admin_editor' => 'system.admin_content',
  ];
  $user_role_routes = array_intersect_key(
    $role_route_map,
    // We need the role names as keys to do an intersect.
    array_flip($account->getRoles())
  );
  $route = array_shift($user_role_routes);
  if (!empty($route)) {
    $url = new Url($route);
    $redirect = new RedirectResponse($url->toString());
    $redirect->send();
  }
}

/**
 * Implements hook_element_info_alter().
 *
 * Add our own library to the toolbar so we can define icons for custom links.
 */
function dbcdk_community_element_info_alter(array &$types) {
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'dbcdk_community/toolbar';
  }
}

/**
 * Implements hook_toolbar_alter().
 *
 * Remove the "home" item since we don't have any front-end to direct the user
 * back to.
 */
function dbcdk_community_toolbar_alter(&$items) {
  if (isset($items['home'])) {
    unset($items['home']);
  }
}

/**
 * Implements hook_link_alter().
 */
function dbcdk_community_link_alter(&$variables) {
  // Make all external links open in a new window.
  /* @var \Drupal\Core\Url $url */
  $url = $variables['url'];
  if ($url->isExternal()) {
    $variables['options']['attributes']['target'] = '_blank';
  }
}
