tools:
  eslint:
    use_native_config: true

checks:
  php:
    excluded_dependencies:
      # Scrutinizer fails when analyzing Drupal Core so exclude it.
      - drupal/core

build:
  environment:
    php: '5.6.16'
    node: 'v4.2.2'
  dependencies:
    after:
      - 'npm install -g eslint'
  tests:
    override:
      -
        command: 'composer phpunit-custom-clover'
        coverage:
          file: 'tests/reports/clover.xml'
          format: 'php-clover'
      -
        command: 'composer phpcs-checkstyle'
        analysis:
          file: 'tests/reports/phpcs-checkstyle.xml'
          format: 'php-cs-checkstyle'

build_failure_conditions:
  # No new issues allowed.
  - 'issues.new.exists'

filter:
    paths:
      - 'web/modules/custom/*'
      - 'web/profiles/custom/*'
      - 'web/themes/custom/*'
