tools:
  php_code_sniffer:
    extensions:
      - inc
      - install
      - module
      - php
      - profile
      - test
      - theme
  eslint:
    use_native_config: true
build_failure_conditions:
  # No new issues allowed.
  - 'issues.new.exists'
before_commands:
  # Install an up-to-date eslint.
  - 'npm install -g eslint'

checks:
  php:
    custom_coding_standard:
      ruleset_path: 'vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml'

filter:
    paths:
      - 'web/modules/custom/*'
      - 'web/profiles/custom/*'
      - 'web/themes/custom/*'
