build:
  environment:
    php: '5.6.16'
    node: 'v4.2.2'
  dependencies:
    before:
      - 'composer global require hirak/prestissimo'
    after:
      - 'npm install -g eslint'

tools:
  php_code_sniffer:
    extensions:
      - inc
      - install
      - module
      - php
      - profile
      - test
      - theme
  eslint:
    use_native_config: true

checks:
  php:
    custom_coding_standard:
      ruleset_path: '../vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml'

filter:
    paths:
      - 'web/modules/custom/*'
      - 'web/profiles/custom/*'
      - 'web/themes/custom/*'

build_failure_conditions:
  # No new issues allowed.
  - 'issues.new.exists'
