web:
  build: .
  dockerfile: docker/web/Dockerfile
  ports:
    - '80/tcp'
  volumes:
    - './web:/var/www/web'
    - './vendor:/var/www/vendor'
    - './docker/docker.settings.php:/var/www/html/sites/default/settings.php:ro'
    - './docker/docker.services.yml:/var/www/html/sites/default/services.yml:ro'
  working_dir: '/var/www/web'
  links:
    - db
db:
  image: mariadb
  ports:
    - '3306/tcp'
  volumes:
    - './docker/db/db.sql.gz:/docker-entrypoint-initdb.d/db.sql.gz:ro'
  environment:
    MYSQL_ROOT_PASSWORD: v6o73qsjBQpbNjaH
    MYSQL_DATABASE: db
    MYSQL_USER: db
    MYSQL_PASSWORD: bP4pFxUvFcF2b1bV
