<?php
/**
 * @file
 * Module file for DBCDK Community Moderation.
 */

/**
 * Implements hook_theme().
 */
function dbcdk_community_moderation_theme($existing, $type, $theme, $path) {
  return [
    'dbcdk_community_moderation__flagged_content__content' => [
      'variables' => [
        'content' => NULL,
        'image_collection_count' => NULL,
        'video_collection_count' => NULL,
      ],
    ],
  ];
}
