<?php
/**
 * CommunityRoleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * communityservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DBCDK\CommunityServices;

use \DBCDK\CommunityServices\Configuration;
use \DBCDK\CommunityServices\ApiClient;
use \DBCDK\CommunityServices\ApiException;
use \DBCDK\CommunityServices\ObjectSerializer;

/**
 * CommunityRoleApiTest Class Doc Comment
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CommunityRoleApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for communityRoleCount
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testCommunityRoleCount()
    {

    }

    /**
     * Test case for communityRoleCreate
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testCommunityRoleCreate()
    {

    }

    /**
     * Test case for communityRoleCreateChangeStreamGetCommunityRolesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testCommunityRoleCreateChangeStreamGetCommunityRolesChangeStream()
    {

    }

    /**
     * Test case for communityRoleCreateChangeStreamPostCommunityRolesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testCommunityRoleCreateChangeStreamPostCommunityRolesChangeStream()
    {

    }

    /**
     * Test case for communityRoleDeleteById
     *
     * Delete a model instance by id from the data source..
     *
     */
    public function testCommunityRoleDeleteById()
    {

    }

    /**
     * Test case for communityRoleExistsGetCommunityRolesidExists
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testCommunityRoleExistsGetCommunityRolesidExists()
    {

    }

    /**
     * Test case for communityRoleExistsHeadCommunityRolesid
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testCommunityRoleExistsHeadCommunityRolesid()
    {

    }

    /**
     * Test case for communityRoleFind
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testCommunityRoleFind()
    {

    }

    /**
     * Test case for communityRoleFindById
     *
     * Find a model instance by id from the data source..
     *
     */
    public function testCommunityRoleFindById()
    {

    }

    /**
     * Test case for communityRoleFindOne
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testCommunityRoleFindOne()
    {

    }

    /**
     * Test case for communityRolePrototypeUpdateAttributes
     *
     * Update attributes for a model instance and persist it into the data source..
     *
     */
    public function testCommunityRolePrototypeUpdateAttributes()
    {

    }

    /**
     * Test case for communityRoleUpdateAll
     *
     * Update instances of the model matched by where from the data source..
     *
     */
    public function testCommunityRoleUpdateAll()
    {

    }

    /**
     * Test case for communityRoleUpsert
     *
     * Update an existing model instance or insert a new one into the data source..
     *
     */
    public function testCommunityRoleUpsert()
    {

    }

}
