<?php
/**
 * FileContainerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * communityservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DBCDK\CommunityServices;

use \DBCDK\CommunityServices\Configuration;
use \DBCDK\CommunityServices\ApiClient;
use \DBCDK\CommunityServices\ApiException;
use \DBCDK\CommunityServices\ObjectSerializer;

/**
 * FileContainerApiTest Class Doc Comment
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileContainerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for fileContainerCount
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testFileContainerCount()
    {

    }

    /**
     * Test case for fileContainerCreate
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testFileContainerCreate()
    {

    }

    /**
     * Test case for fileContainerCreateChangeStreamGetFileContainersChangeStream
     *
     * Create a change stream..
     *
     */
    public function testFileContainerCreateChangeStreamGetFileContainersChangeStream()
    {

    }

    /**
     * Test case for fileContainerCreateChangeStreamPostFileContainersChangeStream
     *
     * Create a change stream..
     *
     */
    public function testFileContainerCreateChangeStreamPostFileContainersChangeStream()
    {

    }

    /**
     * Test case for fileContainerDeleteById
     *
     * Delete a model instance by id from the data source..
     *
     */
    public function testFileContainerDeleteById()
    {

    }

    /**
     * Test case for fileContainerDestroyContainer
     *
     * .
     *
     */
    public function testFileContainerDestroyContainer()
    {

    }

    /**
     * Test case for fileContainerDownload
     *
     * .
     *
     */
    public function testFileContainerDownload()
    {

    }

    /**
     * Test case for fileContainerExistsGetFileContainersidExists
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testFileContainerExistsGetFileContainersidExists()
    {

    }

    /**
     * Test case for fileContainerExistsHeadFileContainersid
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testFileContainerExistsHeadFileContainersid()
    {

    }

    /**
     * Test case for fileContainerFind
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testFileContainerFind()
    {

    }

    /**
     * Test case for fileContainerFindById
     *
     * Find a model instance by id from the data source..
     *
     */
    public function testFileContainerFindById()
    {

    }

    /**
     * Test case for fileContainerFindOne
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testFileContainerFindOne()
    {

    }

    /**
     * Test case for fileContainerGetContainer
     *
     * .
     *
     */
    public function testFileContainerGetContainer()
    {

    }

    /**
     * Test case for fileContainerGetFile
     *
     * .
     *
     */
    public function testFileContainerGetFile()
    {

    }

    /**
     * Test case for fileContainerGetFiles
     *
     * .
     *
     */
    public function testFileContainerGetFiles()
    {

    }

    /**
     * Test case for fileContainerPrototypeUpdateAttributes
     *
     * Update attributes for a model instance and persist it into the data source..
     *
     */
    public function testFileContainerPrototypeUpdateAttributes()
    {

    }

    /**
     * Test case for fileContainerRemoveFile
     *
     * .
     *
     */
    public function testFileContainerRemoveFile()
    {

    }

    /**
     * Test case for fileContainerUpdateAll
     *
     * Update instances of the model matched by where from the data source..
     *
     */
    public function testFileContainerUpdateAll()
    {

    }

    /**
     * Test case for fileContainerUpload
     *
     * .
     *
     */
    public function testFileContainerUpload()
    {

    }

    /**
     * Test case for fileContainerUpsert
     *
     * Update an existing model instance or insert a new one into the data source..
     *
     */
    public function testFileContainerUpsert()
    {

    }

}
