<?php
/**
 * GroupProfileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * communityservice
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DBCDK\CommunityServices;

use \DBCDK\CommunityServices\Configuration;
use \DBCDK\CommunityServices\ApiClient;
use \DBCDK\CommunityServices\ApiException;
use \DBCDK\CommunityServices\ObjectSerializer;

/**
 * GroupProfileApiTest Class Doc Comment
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupProfileApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for groupProfileCount
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testGroupProfileCount()
    {

    }

    /**
     * Test case for groupProfileCreate
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testGroupProfileCreate()
    {

    }

    /**
     * Test case for groupProfileCreateChangeStreamGetGroupProfilesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testGroupProfileCreateChangeStreamGetGroupProfilesChangeStream()
    {

    }

    /**
     * Test case for groupProfileCreateChangeStreamPostGroupProfilesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testGroupProfileCreateChangeStreamPostGroupProfilesChangeStream()
    {

    }

    /**
     * Test case for groupProfileDeleteById
     *
     * Delete a model instance by id from the data source..
     *
     */
    public function testGroupProfileDeleteById()
    {

    }

    /**
     * Test case for groupProfileExistsGetGroupProfilesidExists
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testGroupProfileExistsGetGroupProfilesidExists()
    {

    }

    /**
     * Test case for groupProfileExistsHeadGroupProfilesid
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testGroupProfileExistsHeadGroupProfilesid()
    {

    }

    /**
     * Test case for groupProfileFind
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testGroupProfileFind()
    {

    }

    /**
     * Test case for groupProfileFindById
     *
     * Find a model instance by id from the data source..
     *
     */
    public function testGroupProfileFindById()
    {

    }

    /**
     * Test case for groupProfileFindOne
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testGroupProfileFindOne()
    {

    }

    /**
     * Test case for groupProfilePrototypeGetGroup
     *
     * Fetches belongsTo relation group..
     *
     */
    public function testGroupProfilePrototypeGetGroup()
    {

    }

    /**
     * Test case for groupProfilePrototypeGetProfile
     *
     * Fetches belongsTo relation profile..
     *
     */
    public function testGroupProfilePrototypeGetProfile()
    {

    }

    /**
     * Test case for groupProfilePrototypeUpdateAttributes
     *
     * Update attributes for a model instance and persist it into the data source..
     *
     */
    public function testGroupProfilePrototypeUpdateAttributes()
    {

    }

    /**
     * Test case for groupProfileUpdateAll
     *
     * Update instances of the model matched by where from the data source..
     *
     */
    public function testGroupProfileUpdateAll()
    {

    }

    /**
     * Test case for groupProfileUpsert
     *
     * Update an existing model instance or insert a new one into the data source..
     *
     */
    public function testGroupProfileUpsert()
    {

    }

}
