<?php
/**
 * LikeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * communityservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DBCDK\CommunityServices;

use \DBCDK\CommunityServices\Configuration;
use \DBCDK\CommunityServices\ApiClient;
use \DBCDK\CommunityServices\ApiException;
use \DBCDK\CommunityServices\ObjectSerializer;

/**
 * LikeApiTest Class Doc Comment
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LikeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for likeCount
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testLikeCount()
    {

    }

    /**
     * Test case for likeCreate
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testLikeCreate()
    {

    }

    /**
     * Test case for likeCreateChangeStreamGetLikesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testLikeCreateChangeStreamGetLikesChangeStream()
    {

    }

    /**
     * Test case for likeCreateChangeStreamPostLikesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testLikeCreateChangeStreamPostLikesChangeStream()
    {

    }

    /**
     * Test case for likeDeleteById
     *
     * Delete a model instance by id from the data source..
     *
     */
    public function testLikeDeleteById()
    {

    }

    /**
     * Test case for likeExistsGetLikesidExists
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testLikeExistsGetLikesidExists()
    {

    }

    /**
     * Test case for likeExistsHeadLikesid
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testLikeExistsHeadLikesid()
    {

    }

    /**
     * Test case for likeFind
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testLikeFind()
    {

    }

    /**
     * Test case for likeFindById
     *
     * Find a model instance by id from the data source..
     *
     */
    public function testLikeFindById()
    {

    }

    /**
     * Test case for likeFindOne
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testLikeFindOne()
    {

    }

    /**
     * Test case for likePrototypeGetPost
     *
     * Fetches belongsTo relation post..
     *
     */
    public function testLikePrototypeGetPost()
    {

    }

    /**
     * Test case for likePrototypeGetReview
     *
     * Fetches belongsTo relation review..
     *
     */
    public function testLikePrototypeGetReview()
    {

    }

    /**
     * Test case for likePrototypeUpdateAttributes
     *
     * Update attributes for a model instance and persist it into the data source..
     *
     */
    public function testLikePrototypeUpdateAttributes()
    {

    }

    /**
     * Test case for likeUpdateAll
     *
     * Update instances of the model matched by where from the data source..
     *
     */
    public function testLikeUpdateAll()
    {

    }

    /**
     * Test case for likeUpsert
     *
     * Update an existing model instance or insert a new one into the data source..
     *
     */
    public function testLikeUpsert()
    {

    }

}
