<?php
/**
 * QuarantineApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * communityservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DBCDK\CommunityServices;

use \DBCDK\CommunityServices\Configuration;
use \DBCDK\CommunityServices\ApiClient;
use \DBCDK\CommunityServices\ApiException;
use \DBCDK\CommunityServices\ObjectSerializer;

/**
 * QuarantineApiTest Class Doc Comment
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuarantineApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for quarantineCheckIfProfileIsQuarantined
     *
     * Check if a profile is quarantined.
     *
     */
    public function testQuarantineCheckIfProfileIsQuarantined()
    {

    }

    /**
     * Test case for quarantineCount
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testQuarantineCount()
    {

    }

    /**
     * Test case for quarantineCreate
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testQuarantineCreate()
    {

    }

    /**
     * Test case for quarantineCreateChangeStreamGetQuarantinesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testQuarantineCreateChangeStreamGetQuarantinesChangeStream()
    {

    }

    /**
     * Test case for quarantineCreateChangeStreamPostQuarantinesChangeStream
     *
     * Create a change stream..
     *
     */
    public function testQuarantineCreateChangeStreamPostQuarantinesChangeStream()
    {

    }

    /**
     * Test case for quarantineDeleteById
     *
     * Delete a model instance by id from the data source..
     *
     */
    public function testQuarantineDeleteById()
    {

    }

    /**
     * Test case for quarantineExistsGetQuarantinesidExists
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testQuarantineExistsGetQuarantinesidExists()
    {

    }

    /**
     * Test case for quarantineExistsHeadQuarantinesid
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testQuarantineExistsHeadQuarantinesid()
    {

    }

    /**
     * Test case for quarantineFind
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testQuarantineFind()
    {

    }

    /**
     * Test case for quarantineFindById
     *
     * Find a model instance by id from the data source..
     *
     */
    public function testQuarantineFindById()
    {

    }

    /**
     * Test case for quarantineFindOne
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testQuarantineFindOne()
    {

    }

    /**
     * Test case for quarantinePrototypeGetCreator
     *
     * Fetches belongsTo relation creator..
     *
     */
    public function testQuarantinePrototypeGetCreator()
    {

    }

    /**
     * Test case for quarantinePrototypeGetQuarantined
     *
     * Fetches belongsTo relation quarantined..
     *
     */
    public function testQuarantinePrototypeGetQuarantined()
    {

    }

    /**
     * Test case for quarantinePrototypeUpdateAttributes
     *
     * Update attributes for a model instance and persist it into the data source..
     *
     */
    public function testQuarantinePrototypeUpdateAttributes()
    {

    }

    /**
     * Test case for quarantineUpdateAll
     *
     * Update instances of the model matched by where from the data source..
     *
     */
    public function testQuarantineUpdateAll()
    {

    }

    /**
     * Test case for quarantineUpsert
     *
     * Update an existing model instance or insert a new one into the data source..
     *
     */
    public function testQuarantineUpsert()
    {

    }

}
