<?php
/**
 * ResolutionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * communityservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DBCDK\CommunityServices;

use \DBCDK\CommunityServices\Configuration;
use \DBCDK\CommunityServices\ApiClient;
use \DBCDK\CommunityServices\ApiException;
use \DBCDK\CommunityServices\ObjectSerializer;

/**
 * ResolutionApiTest Class Doc Comment
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResolutionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for resolutionCount
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testResolutionCount()
    {

    }

    /**
     * Test case for resolutionCreate
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testResolutionCreate()
    {

    }

    /**
     * Test case for resolutionCreateChangeStreamGetResolutionsChangeStream
     *
     * Create a change stream..
     *
     */
    public function testResolutionCreateChangeStreamGetResolutionsChangeStream()
    {

    }

    /**
     * Test case for resolutionCreateChangeStreamPostResolutionsChangeStream
     *
     * Create a change stream..
     *
     */
    public function testResolutionCreateChangeStreamPostResolutionsChangeStream()
    {

    }

    /**
     * Test case for resolutionDeleteById
     *
     * Delete a model instance by id from the data source..
     *
     */
    public function testResolutionDeleteById()
    {

    }

    /**
     * Test case for resolutionExistsGetResolutionsidExists
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testResolutionExistsGetResolutionsidExists()
    {

    }

    /**
     * Test case for resolutionExistsHeadResolutionsid
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testResolutionExistsHeadResolutionsid()
    {

    }

    /**
     * Test case for resolutionFind
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testResolutionFind()
    {

    }

    /**
     * Test case for resolutionFindById
     *
     * Find a model instance by id from the data source..
     *
     */
    public function testResolutionFindById()
    {

    }

    /**
     * Test case for resolutionFindOne
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testResolutionFindOne()
    {

    }

    /**
     * Test case for resolutionPrototypeCreateImage
     *
     * Creates a new instance in image of this model..
     *
     */
    public function testResolutionPrototypeCreateImage()
    {

    }

    /**
     * Test case for resolutionPrototypeCreateVideo
     *
     * Creates a new instance in video of this model..
     *
     */
    public function testResolutionPrototypeCreateVideo()
    {

    }

    /**
     * Test case for resolutionPrototypeDestroyImage
     *
     * Deletes image of this model..
     *
     */
    public function testResolutionPrototypeDestroyImage()
    {

    }

    /**
     * Test case for resolutionPrototypeDestroyVideo
     *
     * Deletes video of this model..
     *
     */
    public function testResolutionPrototypeDestroyVideo()
    {

    }

    /**
     * Test case for resolutionPrototypeGetImage
     *
     * Fetches hasOne relation image..
     *
     */
    public function testResolutionPrototypeGetImage()
    {

    }

    /**
     * Test case for resolutionPrototypeGetVideo
     *
     * Fetches hasOne relation video..
     *
     */
    public function testResolutionPrototypeGetVideo()
    {

    }

    /**
     * Test case for resolutionPrototypeUpdateAttributes
     *
     * Update attributes for a model instance and persist it into the data source..
     *
     */
    public function testResolutionPrototypeUpdateAttributes()
    {

    }

    /**
     * Test case for resolutionPrototypeUpdateImage
     *
     * Update image of this model..
     *
     */
    public function testResolutionPrototypeUpdateImage()
    {

    }

    /**
     * Test case for resolutionPrototypeUpdateVideo
     *
     * Update video of this model..
     *
     */
    public function testResolutionPrototypeUpdateVideo()
    {

    }

    /**
     * Test case for resolutionUpdateAll
     *
     * Update instances of the model matched by where from the data source..
     *
     */
    public function testResolutionUpdateAll()
    {

    }

    /**
     * Test case for resolutionUpsert
     *
     * Update an existing model instance or insert a new one into the data source..
     *
     */
    public function testResolutionUpsert()
    {

    }

}
